### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by o9mniej** [Zabuzard/Discord-Plays#13]
i got it installd and it doesnot work help

**Comment by Zabuzard** [comment]
Hey there. Said to hear that, I am sure we can get it going together.

Please share more details of what you did and whats going wrong specifically. Perhaps you can share some screenshots, error messages and a step by step list of what you did 🙂

**Comment by o9mniej** [comment]
there arent eny errors the bot turns on but commands dont work

**Comment by Zabuzard** [comment]
could you be more specific please? it works for me.
